FIELDS_MASTER = [
    'm_dataset', 'm_pseudoid', 'm_camp', 'm_lastname', 'm_firstname', 'm_birthyear', 'm_gender',
    'm_originalstate', 'm_familyno', 'm_individualno',
]

# order of fields in far-ancestry.csv
FIELDS_ANCESTRY = [
    'm_pseudoid', 'm_camp', 'm_lastname', 'm_firstname', 'm_birthyear', 'm_gender',
    'm_originalstate', 'm_familyno', 'm_individualno',
    'f_othernames', 'f_maritalstatus', 'f_citizenship', 'f_alienregistration',
    'f_entrytype', 'f_entrydate', 'f_departuretype', 'f_departuredate',
    'f_destinationcity', 'f_destinationstate', 'f_campaddress', 'f_farlineid',
]

# order of fields in far-manzanar.csv, far-minidoka.csv, far-poston.csv
FIELDS_CAMPS = [
    'm_dataset', 'm_pseudoid', 'm_camp', 'm_lastname', 'm_firstname', 'm_birthyear',
    'm_gender', 'm_originalstate', 'm_familyno', 'm_individualno',
    'f_othernames', 'f_maritalstatus', 'f_citizenship', 'f_alienregistration',
    'f_entrytype', 'f_entrydate', 'f_originalcity', 'f_departuretype',
    'f_departuredate', 'f_destinationcity', 'f_destinationstate', 'f_campaddress',
    'f_farlineid',
]

FIELDS_WRA = [
    'm_pseudoid', 'm_camp', 'm_lastname', 'm_firstname', 'm_birthyear',
    'm_gender', 'm_originalstate', 'm_familyno', 'm_individualno',
    'w_assemblycenter', 'w_originaladdress', 'w_birthcountry', 'w_fatheroccup',
    'w_fatheroccupcat', 'w_yearsschooljapan', 'w_gradejapan', 'w_schooldegree',
    'w_yearofusarrival', 'w_timeinjapan', 'w_notimesinjapan', 'w_ageinjapan',
    'w_militaryservice', 'w_maritalstatus', 'w_ethnicity', 'w_birthplace',
    'w_citizenshipstatus', 'w_highestgrade', 'w_language', 'w_religion',
    'w_occupqual1', 'w_occupqual2', 'w_occupqual3', 'w_occuppotn1', 'w_occuppotn2',
    'w_filenumber',
]

DATASETS = {
    'far-ancestry': FIELDS_ANCESTRY,
    'far-manzanar': FIELDS_CAMPS,
    'far-minidoka': FIELDS_CAMPS,
    'far-poston': FIELDS_CAMPS,
    'wra-master': FIELDS_WRA,
}

FIELD_DEFINITIONS = {
    'm_dataset': {
	'label': 'Data source',
        'description': 'ID of dataset. Uses controlled vocabulary.',
        'type': 'string',
        'required': True,
        'sample': 'far-ancestry',
        'notes': 'far-ancestry|far-poston|far-minidoka|far-manzanar|wra',
    },
    'm_pseudo_id': {
	'label': 'Pseudo ID',
        'description': 'Consolidated derived ID',
        'type': 'string',
        'required': True,
        'sample': '2-poston_akiyama_1888_kiyomi',
        'notes': '',
    },
    'm_camp': {
        'label': 'Camp',
        'description': 'Primary concentration camp. Uses Densho shared controlled vocabulary.',
        'type': 'string',
        'required': True,
        'sample': '2-poston',
        'notes': '',
    },
    'm_lastname': {
        'label': 'Last name',
        'description': 'Last name',
        'type': 'string',
        'required': False,
        'sample': 'Miura',
        'notes': '',
    },
    'm_firstname': {
	'label': 'First name',
        'description': 'First name',
        'type': 'string',
        'required': False,
        'sample': 'George',
        'notes': '',
    },
    'm_birthyear': {
	'label': 'Birth year',
        'description': 'Birth year',
        'type': 'number',
        'required': False,
        'sample': '1921',
        'notes': '',
    },
    'm_gender': {
	'label': 'Gender',
        'description': 'Gender',
        'type': 'string',
        'required': True,
        'sample': 'M',
        'notes': '',
    },
    'm_originalstate': {
	'label': 'State of residence at time of removal',
        'description': 'State of residence at time of removal',
        'type': 'string',
        'required': False,
        'sample': 'Utah',
        'notes': 'Not included in far-ancestry data',
    },
    'm_familyno': {
	'label': 'WRA family number',
        'description': 'WRA-assigned family ID',
        'type': 'string',
        'required': False,
        'sample': '34339',
        'notes': 'Not included in far-ancestry data',
    },
    'm_individualno': {
	'label': 'WRA individual number',
        'description': 'WRA-assigned individual ID',
        'type': 'string',
        'required': False,
        'sample': '34339B',
        'notes': 'Not included in far-ancestry data',
    },
    
    'f_originalcity': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_othernames': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_maritalstatus': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_citizenship': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_alienregistration': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_entrytype': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_entrydate': {
        'label': '',
        'description': '',
        'type': 'date',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_departuretype': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_departuredate': {
        'label': '',
        'description': '',
        'type': 'date',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_destinationstate': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_destinationcity': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_campaddress': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'f_farlineid': {
        'label': '',
        'description': '',
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    
    'w_assemblycenter': {
        'label': "Assembly Center",
        'description': "Original: Assem Center",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_originaladdress': {
        'label': "Residence at time of removal",
        'description': "Original: Prev Address",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_birthcountry': {
        'label': "Country of birth",
        'description': "Original:Birth Country",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_fatheroccup': {
        'label': "Father's occupation",
        'description': "Original: Father Occ US",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_fatheroccupcat': {
        'label': "Father's occupation category",
        'description': "Original:Father Occ Abr",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_yearsschooljapan': {
        'label': "Years of schooling in Japan",
        'description': "Original: Yrs School Jpn",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_gradejapan': {
        'label': "Grade in Japan",
        'description': "Original: Grade In Japan",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_schooldegree': {
        'label': "Degree achieved",
        'description': "Original: School Degree",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_yearofusarrival': {
        'label': "Year of US arrival",
        'description': "Original: Yr US Arrival",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_timejapan': {
        'label': "Time in Japan",
        'description': "Original: Time in Japan",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_notimesjapan': {
        'label': "Number of times in Japan",
        'description': "Original: No# Times Jpn",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_agejapan': {
        'label': "Age in Japan",
        'description': "Original:Age In Japan",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_militaryservice': {
        'label': "Military service",
        'description': "Original: Military, etc#",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_maritalstatus': {
        'label': "Marital status",
        'description': "Original: Sex & Marital",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_ethnicity': {
        'label': "Ethnicity",
        'description': "Original: Race",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_birthplace': {
        'label': "Birthplace",
        'description': "Original: Birthplace",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_citizenshipstatus': {
        'label': "Citizenship status",
        'description': "Original: Alien #, SS#",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_highestgrade': {
        'label': "Highest grade achieved",
        'description': "Original: Highest Grade",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_language': {
        'label': "Languages",
        'description': "Original: Language",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_religion': {
        'label': "Religion",
        'description': "Original: Religion",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_occupqual1': {
        'label': "Occupation Qualification Primary",
        'description': "Original: Occup Qual 1",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_occupqual2': {
        'label': "Occupation Qualification Secondary",
        'description': "Original: Occup Qual 2",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_occupqual3': {
        'label': "Occupation Qualification Tertiary",
        'description': "Original: Occup Qual 3",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_occuppotn1': {
        'label': "Potential Occupation Primary",
        'description': "Original: Occup Potn 1",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_occuppotn2': {
        'label': "Potential Occupation Secondary",
        'description': "Original: Occup Potn 2",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
    'w_filenumber': {
        'label': "File Number",
        'description': "Original: File Number",
        'type': 'string',
        'required': False,
        'sample': '',
        'notes': '',
    },
}
